### ISSUE TITLE
Trying to generate images using pre-trained model

### ISSUE THREAD

**Issue by JikkuJose** [paarthneekhara/text-to-image#2]
#### What I did

- Downloaded the pre-trained model
- Created a file (_j.caption_) with a sample caption
- Ran: `python generate_thought_vectors.py --caption_file=j.caption`
- Got the following error, any ideas?

```
['pink flower with green leaves']
Loading model parameters...
Traceback (most recent call last):
  File "generate_thought_vectors.py", line 32, in <module>
    main()
  File "generate_thought_vectors.py", line 23, in main
    model = skipthoughts.load_model()
  File "/Users/jikkujose/Projects/outside_projects/text-to-image/skipthoughts.py", line 38, in load_model
    with open('%s.pkl'%path_to_umodel, 'rb') as f:
```

#### Specs

- Mac OSX 10.11.6
- Python 2.7.11

**Comment by paarthneekhara** [comment]
I think you did not download the skipthought vectors pretrained models. Download all the files from this link.. [https://github.com/ryankiros/skip-thoughts#getting-started][1], and save them in ```Data/skipthoughts``` as given in the project's readme. Let me know if you face any other problem.
[1]:https://github.com/ryankiros/skip-thoughts#getting-started

**Comment by JikkuJose** [comment]
Oh yes! Missed that, thanks!
