### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by JamesChuanggg** [paarthneekhara/text-to-image#3]
Hi,
First of all, thanks for your awesome work! I'm wondering that is there any evaluation metrics for this kind of generative model since I want to compare the performance between using Skip Thought Vectors and the other embedding options for captions.

**Comment by paarthneekhara** [comment]
Hi,
Thanks for your appreciation! As per the paper, I did not see any metric for evaluation of the generated images. There is only a qualitative comparison between the various generative models, by generating images from unseen captions. If you want to go ahead comparing different embedding options for captions, I strongly recommend also trying training them along with the model (this is suggested in the paper). A qualitative comparison can be made between different caption embeddings, as done between different generative models in the paper.

**Comment by JamesChuanggg** [comment]
thanks for your reply. Got the point!
