### ISSUE TITLE
Input of Discriminator

### ISSUE THREAD

**Issue by JamesChuanggg** [paarthneekhara/text-to-image#4]
Hi, here's another question.
[Here](https://github.com/paarthneekhara/text-to-image/blob/master/model.py#L40) the discriminator's input is wrong image and right text. However according to the original paper (page 5), they use real image and wrong text which is different from your implementation.

**Comment by paarthneekhara** [comment]
Hi,
The discriminator has to learn to identify real images with the right text (output should be 1). The output should be 0 if the text does not match with the image, or if the image is fake (generated). Right Image with wrong text is equivalent to wrong image with right text (i.e image and text do not correspond to each other). Wrong image and right text, are used in the implementation of the paper as well (https://github.com/reedscot/icml2016). It just an implmentation convinience.

**Comment by JamesChuanggg** [comment]
Thanks for your reply! Really helps me a lot.
